ALTER TABLE IF EXISTS noteful_notes
    DROP COLUMN folderid; 

DROP TABLE IF EXISTS noteful_folders;
DROP TABLE IF EXISTS noteful_notes; 

CREATE TABLE noteful_folders(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL

);


CREATE TABLE noteful_notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    content TEXT,
    date_modified TIMESTAMPTZ DEFAULT now() NOT NULL
    
);

ALTER TABLE noteful_folders 
    ADD COLUMN folderid INTEGER REFERENCES noteful_folders(id);
